//tealium universal tag - utag.660 ut4.0.202006221800, Copyright 2020 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={"merkle_mid":"MID","product_selling_price_discount":"product_unit_price"};u.extend=[function(a,b,c,d,e,f,g){if(1){d=b['cp.urbn_language'];if(typeof d=='undefined')return;c=[{'en-GB':'freepeopleuk'}];var m=false;for(e=0;e<c.length;e++){for(f in utag.loader.GV(c[e])){g=new RegExp(f,'i');if(g.test(d)){b['merkle_mid']=c[e][f];m=true};};if(m)break};if(!m)b['merkle_mid']='freepeople';}},function(a,b){try{if((typeof b['page_type']!='undefined'&&b['page_type'].toString().toLowerCase().indexOf('confirmation'.toLowerCase())<0)||(typeof b['page_type']!='undefined'&&b['page_type'].toString().toLowerCase().indexOf('receipt'.toLowerCase())<0)){try{b['order_id']=""}catch(e){}}}catch(e){utag.DB(e);}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={"base_url":"//cdn.merklesearch.com/merkle_track.js","MID":'',"product_sku":[],"product_unit_price":[],"product_quantity":[],"product_name":[],"conversion_time":"","date":"","micro_conversion_type":"","micro_conversion_value":""};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){if(typeof utag_err!='undefined'){utag_err.push({e:'extension error:'+e,s:utag.cfg.path+'utag.'+id+'.js',l:c,t:'ex'})}}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
u.data.order_id=u.data.order_id||b._corder||"";u.data.client_id=u.data.client_id||b._ccustid||"";if(u.data.product_sku.length===0&&b._csku!==undefined){u.data.product_sku=b._csku.slice(0);}
if(u.data.product_unit_price.length===0&&b._cprice!==undefined){u.data.product_unit_price=b._cprice.slice(0);}
if(u.data.product_quantity.length===0&&b._cquan!==undefined){u.data.product_quantity=b._cquan.slice(0);}
if(u.data.product_name.length===0&&b._cprodname!==undefined){u.data.product_name=b._cprodname.slice(0);}
(function(){if(u.data.conversion_time==""){var f=new Date();d=f.getMonth()+1;if(d<10){d='0'+d;}
e=f.getDate();if(e<10){e='0'+e;}
u.data.conversion_time=''+f.getFullYear()+d+e+f.getHours()+''+f.getMinutes()+''+f.getSeconds();}}());u.loader_cb=function(){u.initialized=true;if(u.data.order_id){try{for(var i=0;i<u.data.product_sku.length;i++){var sendOrderData={};sendOrderData['mid']=u.data.MID;sendOrderData['oid']=u.data.order_id;sendOrderData['lid']=i+1;sendOrderData['lid']=sendOrderData['lid'].toString();if(u.data.client_id){sendOrderData['cid']=u.data.client_id;}
sendOrderData['iid']=u.data.product_sku[i];sendOrderData['icent']=parseFloat(u.data.product_unit_price[i])*100;sendOrderData['icent']=sendOrderData['icent'].toString();sendOrderData['iqty']=u.data.product_quantity[i];sendOrderData['iname']=u.data.product_name[i];if(u.data.conversion_time){sendOrderData['ts']=u.data.conversion_time;}
merklesearch.sendOrder(sendOrderData);console.log(sendOrderData);}}catch(e){console.log(e.message,e.name);}}else if(u.data.micro_conversion_type){(function(){var microConversionData={};microConversionData['mid']=u.data.MID;microConversionData['type']=u.data.micro_conversion_type;if(u.data.micro_conversion_value){microConversionData['valcent']=u.data.micro_conversion_value;}
if(u.data.client_id){microConversionData['cid']=u.data.client_id;}
merklesearch.sendMicro(microConversionData);}());}else{try{try{merklesearch.sendAdSid(u.data.MID);}catch(e){}}catch(e){}}
};if(!u.initialized){u.loader({"type":"script","src":u.data.base_url,"cb":u.loader_cb,"loc":"script","id":'utag_660'});}else{u.loader_cb();}
}};utag.o[loader].loader.LOAD(id);})("660","urbanoutfitters.a15-fpweb");}catch(error){utag.DB(error);}
