//tealium universal tag - utag.746 ut4.0.202006221800, Copyright 2020 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={"bluecore_site_id":"bluecore_site_id"};u.extend=[function(a,b){try{if(1){b['bluecore_site_id']='free_people'}}catch(e){utag.DB(e);}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){if(typeof utag_err!='undefined'){utag_err.push({e:'extension error:'+e,s:utag.cfg.path+'utag.'+id+'.js',l:c,t:'ex'})}}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
if(b.customer_email){window.triggermail_email_address=b.customer_email;}
if(!document.getElementById('bluecorepx')){var triggermail=triggermail||[];triggermail.load=function(a){var b=document.createElement("script");b.setAttribute("id","bluecorepx");b.type="text/javascript";b.async=!0;b.src="https://api.bluecore.com/triggermail.js/"+a+".js";a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(b,a)};triggermail.load(b.bluecore_site_id);window.triggermail=triggermail;}
if(b.order_id){var productLength=b.product_url.length;var bcpid="";for(var i=0;i<productLength;i++){bcpid+=b.product_style_number[i];var color=b.product_url[i].split("color=");if(color[1]){bcpid+="-"+color[1].substring(0,3);}
bcpid+=","}
var purchaseBluePixel="https://www.bluecore.com/api/track/purchase_pixel?token="+b.bluecore_site_id+"&email="+b.customer_email+"&total="+b.order_grand_total+"&order_id="+b.order_id+"&product_ids="+bcpid;var xmlHttp=new XMLHttpRequest();xmlHttp.open("GET",purchaseBluePixel);xmlHttp.send();}
}};utag.o[loader].loader.LOAD(id);})("746","urbanoutfitters.a15-fpweb");}catch(error){utag.DB(error);}
